Filter the list of shipments for group captains
distributeaid/shipment-tracker pull request #252
Opened 2021-07-17 18:27 UTC by deammer

Limits which shipments group captains can see in the list. Resolves #130.

Note: I originally assumed it'd be easier to do this on the client, but it was much cleaner to do it on the backend 😅

2021-07-17 20:05 UTC, coderbyheart requested changes

2021-07-17 20:05 UTC, coderbyheart commented on src/resolvers/shipment.ts
> +          status: valid.value.status.filter((status) =>
If captain requests to see a shipment with a status they are not supposed to see, that request should be rejected with a forbidden error.

2021-07-18 10:52 UTC, coderbyheart commented on src/resolvers/shipment.ts
> +    // Group captains can only view a subset of shipments by status
It is not established that the calling user is a group captain.

2021-07-18 10:54 UTC, coderbyheart commented on src/resolvers/shipment.ts
> +          status: valid.value.status.filter((status) =>
If only certain status are allowed for listing, this needs to be applied to fetching individual shiptments.

2021-07-18 11:23 UTC, coderbyheart commented
@deammer I've added tests to the backend logic and changed the API to throw a forbidden error, if a non-admin requests a status they are not supposed to see.

One thing I noticed is that you write about "captains", but at no point was the captain role established. So I changed the wording, to match the actual logic. The limitation now distinguishes between admins and users.

2021-07-18 11:24 UTC, coderbyheart approved these changes

2021-07-18 16:48 UTC, deammer commented
@coderbyheart thank you, I really appreciate your help!

2021-07-18 16:48 UTC, merged

2021-07-18 21:19 UTC, coderbyheart commented
@deammer next time when you are about to merge a PR, please check if you are up to date with saga. The merge resulted in broken code.

2021-07-19 16:26 UTC, deammer commented
That's weird because it's impossible to merge through the UI when a branch is out of date with saga 🤔 

<img width="874" alt="Screen Shot 2021-07-19 at 9 25 34 AM" src="https://user-images.githubusercontent.com/3411183/126194040-ec081f30-cbf1-4319-9639-bfbec3d0c2f4.png">

2021-07-19 16:35 UTC, coderbyheart commented
I think this only applies if there is a conflict. In case of 552bf7eb1f9eff2cf79cf0fcc887093a31ff29af there was no conflict, the changes could be applied.